version: '3.9'
services:
  db:
    image: $DB_IMAGE
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '$DB_ACCESS_PORT:$DB_INTERNAL_PORT'
  backend:
    depends_on:
      - db
    build: ./backend
    container_name: backend-app
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - ./app/node_modules
  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
